spring:
  application:
    name: carrier-prototype
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint.health:
    show-details: ALWAYS
info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'